### ISSUE TITLE
[HP Counter Patch] Updated or Replace Poison Goomba Sprite

### ISSUE THREAD

**Issue by RPGHacker** [RPGHacker/SMW-Workspace#17]
The HP counter patch comes bundled with a sprite for a Poison Goomba with custom damage. However, it seems that this sprite is still in TRASM format and way out-dated. We should either replace it entirely or rewrite it to PIX/GIEPY format.

**Comment by ExE-Boss** [comment]
That’s why I didn’t originally include it when I made PR #5.

**Comment by RPGHacker** [comment]
Fixed in b6797972fc102f8bcde714d572e7f4f6e8fa558c - added a simple Mad Rex PIXI sprite, which deals custom damage based on extra properties.

Unfortunately, the patch itself currently doesn't work properly for me, but I have no idea if it's related to this or if something else broke it (in fact, I'm not quite sure whether the current version of the patch ever worked at all, since I only ever tested it after changing a lot of stuff). It seems as as though the status bar isn't updated correctly, but I don't know what could lead to that.

Anyways, closing this issue since the problems I just mentioned aren't related to it.

**Comment by ExE-Boss** [comment]
> I'm not quite sure whether the current version of the patch ever worked at all, since I only ever tested it after changing a lot of stuff

The version that I had in PR #5 worked on my machine when I opened the PR.

**Comment by RPGHacker** [comment]
I think I've already fixed the problem I had here. If I remember correctly, the problem was that I somehow broke get_status_ram(), which should be fixed now.
