### ISSUE TITLE
VWF Dialogues Patch v1.2 is not compatible with SA-1 Pack v1.31.

### ISSUE THREAD

**Issue by Mintsoda15** [RPGHacker/SMW-Workspace#19]
This patch is not compatible with SA-1 Pack v1.31 and is considered to require an update.
And Lunar Magic 3.01 has the ability to go to over-world in Secondary Entrances, so I cancels the level-out suggestion.

**Comment by RPGHacker** [comment]
Which patch specifically? (I'm currently hosting four different patches in here)

**Comment by HayashiNeru** [comment]
VWF Dialogues 1.2

**Comment by TheLX5** [comment]
add `ldx #$A1` after the `plx` in line 530 in vwf_dialogues.asm to fix the issue, works fine for me.

https://github.com/RPGHacker/SMW-Workspace/blob/master/patches/vwf_dialogues/vwf_dialogues.asm#L530

**Comment by TheLX5** [comment]
alternatively, you could use the two spare bytes at the hijack spot to put the fix instead of incrementing the insert size.

original code
```
org remap_rom($008297)
	jml NMIHijack
	nop #2
```

proposed fix:

```
org remap_rom($008297)
	ldx #$A1
	jml NMIHijack
```

https://github.com/RPGHacker/SMW-Workspace/blob/master/patches/vwf_dialogues/vwf_dialogues.asm#L324

**Comment by TheLX5** [comment]
actually, that just makes it not crash anymore, it still doesn't work properly

at least it doesn't crash, it's a good start i guess 🤷‍♂️

**Comment by TheLX5** [comment]
I tried making this SA-1 hybrid, if someone wants to test it go ahead and tell me if it works fine on SA-1 and non SA-1 ROMs: [vwf_dialogues.zip](https://github.com/RPGHacker/SMW-Workspace/files/2895549/vwf_dialogues.zip)

Once I get a confirmation that this works fine, I'll submit a pull request.

**Comment by TheLX5** [comment]
Actually, I don't have powers to create a pull request, so it's up to you to update the master branch and see if my changes matches your coding style (I've only modified vwf_dialogues.asm). And maybe check if the issue ThePat reported on that screenshot happens on the current version of the patch.

**Comment by RPGHacker** [comment]
Huh, really? That's weird, I thought everyone could do pull requests here? Gotta check if maybe there's some setting I missed.

**Comment by RPGHacker** [comment]
Hmm, I'm not finding any setting for that. Others have made pull requests in the past, though, so I don't quite know why it wouldn't work...

**Comment by TheLX5** [comment]
I actually messed that up, pull request is uploaded. https://github.com/RPGHacker/SMW-Workspace/pull/20

**Comment by RPGHacker** [comment]
I've just merged yoshifanatic's version 1.3 changes into this repository, which should fix the SA-1 pack incompatibility. Don't feel like trying it out myself right now, so if anyone else wants to, let me know and I'll close this issue.

**Comment by MANGOM1LK** [comment]
Current PR only seems to be working in higan, the textbox graphics show up corrupted in bsnes and seems to be setting all Layer 2 and 3 colors to white, not sure if it's related to the layers or to where the palettes are in memory. I'm using Medic's MSU-1 patch alongside this so that might be what's breaking things

**Comment by MANGOM1LK** [comment]
Tried LX5's PR and that doesn't fix it either unfortunately

**Comment by RPGHacker** [comment]
Okay, that's kinda unfortunate.
I'm not very erxperienced with SA-1 code myself, and I currenlty can't even really test things on my sd2snes because I lack some stuff I need to use my SNES. Basically, I'd need someone else's help for this. If someone else can fix this and do a pull request, I'll merge it into the main version.

**Comment by IronFoxGaming** [comment]
I wanted to mention that, while TheLX5's fixed VWF.zip does actually work on SA-1 1-40, it doesn't seem to be compatible with any status bar modifying patches. The messages boxes work exactly how they should, but I'm not sure what the VWF patch does that is so reliant on the vanilla status bar other than hiding it when a message box pops up...

**Comment by IronFoxGaming** [comment]
No, I'm not talking about a cutscene tool. I mean that the SA-1 hybrid TheLX5 posted in this thread on Feb 22, 2019. That one on its own works on an SA-1 1.40 rom.

**Comment by RPGHacker** [comment]
I'm pretty sure VWF Dialogues 1.30 works with the newest SA-1 Pack (tested in 1.40 at least), so I believe this can be closed.
